version: "3.8"

services:
  virtuoso:
    image: tenforce/virtuoso
    container_name: tenforce_virtuoso
    env_file:
      - .env
    ports:
      - "1111:1111"
      - "8890:8890"
    volumes:
      - db:/data

  lodview:
    build: ./lodview
    image: rendxn/lodview
    container_name: lodview
    ports:
      - "8080:8080"

volumes:
  db:
